services:
  db:
    image: mysql:8.0
    container_name: mt_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  wordpress:
    build: .
    container_name: mt_wordpress
    restart: always
    ports:
      - "${WORDPRESS_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);

        define('SCRIPT_DEBUG', false);
        define('MT_DEBUG', false);
        define('SAVEQUERIES', false);
        
        /* File Upload Settings */
        define('WP_TEMP_DIR', '/var/www/html/wp-content/uploads/tmp');
        define('UPLOADS', 'wp-content/uploads');
        
        /* Memory Limits */

        define('WP_MEMORY_LIMIT', '256M');
    volumes:
      - wordpress_data:/var/www/html
      - ../Plugin:/var/www/html/wp-content/plugins/mobility-trailblazers
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    container_name: mt_phpmyadmin
    restart: always
    ports:
      - "${PHPMYADMIN_PORT:-8081}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
  wordpress_data: