services:
  db:
    image: mysql:8.0
    container_name: mt_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wordpress_network

  wordpress:
    build: .
    container_name: mt_wordpress
    restart: always
    ports:
      - "${WORDPRESS_PORT:-8080}:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('FS_METHOD', 'direct');
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('WP_MEMORY_LIMIT', '256M');
    volumes:
      - wordpress_data:/var/www/html
      - ../Plugin:/var/www/html/wp-content/plugins/mobility-trailblazers
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    networks:
      - wordpress_network

  wpcli:
    image: wordpress:cli-php8.2
    container_name: mobility_wpcli_dev
    user: "33:33"
    depends_on:
      - db
      - wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WP_CLI_CACHE_DIR: /var/www/.wp-cli/cache
    volumes:
      - wordpress_data:/var/www/html:rw
      - wordpress_uploads:/var/www/html/wp-content/uploads:rw
      - wordpress_plugins:/var/www/html/wp-content/plugins:rw
    command: tail -f /dev/null
    networks:
      - wordpress_network

volumes:
  db_data:
  wordpress_data:
  wordpress_uploads:
  wordpress_plugins:

networks:
  wordpress_network:
    driver: bridge