name: Block legacy folders (includes/, languages/ at repo root)

on:
  pull_request:
    branches:
      - develop
      - main
      - nightly-build

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Guard against root includes/
        shell: bash
        run: |
          if git diff --name-only origin/${{ github.base_ref }}... | grep -E '^includes/'; then
            echo "Root 'includes/' is not allowed. Use 'Plugin/includes/' instead." >&2
            exit 1
          fi

      - name: Guard against root languages/
        shell: bash
        run: |
          if git diff --name-only origin/${{ github.base_ref }}... | grep -E '^languages/'; then
            echo "Root 'languages/' is not allowed. Use 'Plugin/languages/' instead." >&2
            exit 1
          fi

